# https://sw.kovidgoyal.net/kitty/kittens/diff
foreground           #c0caf5
background           #1a1b26
title_fg             #c0caf5
title_bg             #1a1b26
margin_bg            #292e42
margin_fg            #283457
removed_bg           #f7768e
highlight_removed_bg #f7768e
removed_margin_bg    #f7768e
added_bg             #9ece6a
highlight_added_bg   #9ece6a
added_margin_bg      #9ece6a
filler_bg            #283457
hunk_margin_bg       #283457
hunk_bg              #7aa2f7
search_bg            #7dcfff
search_fg            #1a1b26
select_bg            #e0af68
select_fg            #1a1b26
