# vim:ft=kitty

enable_audio_bell no
update_check_interval 0
confirm_os_window_close 0

background_opacity 0.95
inactive_text_alpha 0.6

cursor_trail 3
cursor_trail_decay 0.1 0.4

font_family monospace
font_size 16

tab_bar_edge top

# see some default keybindings at https://gist.github.com/AskinNet/0d0d4f7f0ee221f8362af9d987
# also be sure to check out the names of the "Boss" class's functions: https://github.com/kovidgoyal/kitty/blob/master/kitty/boss.py
# or see the default mappings directly (look at the map() and mma() functions): https://github.com/kovidgoyal/kitty/blob/master/kitty/options/definition.py
###
kitty_mod ctrl+shift
# new tab in kitty
map kitty_mod+t new_tab_with_cwd
# new window in kitty
map kitty_mod+n new_window_with_cwd
# new OS window
map kitty_mod+enter new_os_window_with_cwd

include kitty_theme

