# cd into a clicked directory and list its contents
protocol file
mime inode/directory
action send_text normal,application cd ${FILE_PATH}\rls\r

# Open any file with a fragment in neovim, currently only used by ripgrep.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current nvim +${FRAGMENT} -- ${FILE_PATH}

# Open image files with icat
protocol file
mime image/*
#action send_text normal,application kitten icat ${FILE_PATH}\r
action launch --type=overlay --cwd=current kitten icat --hold ${FILE_PATH}

# Open audio/video files with mpv
protocol file
mime audio/*,video/*
action launch --type=overlay --cwd=current mpv ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
#mime text/*,application/*
action launch --type=overlay --cwd=current -- ${EDITOR} -- ${FILE_PATH}

