# Open kitty HTML docs links
protocol kitty+doc
action show_kitty_doc ${URL_PATH}

# cd into a clicked directory and list its contents
protocol file
mime inode/directory
action send_text normal,application cd ${FILE_PATH}\rls\r

# Open any file with a fragment in neovim, currently only used by ripgrep.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current nvim +${FRAGMENT} -- ${FILE_PATH}

# special image case with SVG
protocol file
mime image/svg+xml
action launch --type=overlay --cwd=current sh -c 'resvg --image-rendering optimizeSpeed ${FILE_PATH} -c | kitten icat --hold'

# Open image files with icat
protocol file
mime image/*
#action send_text normal,application kitten icat ${FILE_PATH}\r
action launch --type=overlay --cwd=current kitten icat --hold ${FILE_PATH}

# everything not handled here will be handled by xdg-open
# use "send_text" instead of "launch" to reuse the terminal
protocol file
action send_text normal,application xdg-open ${FILE_PATH}\r
