# https://sw.kovidgoyal.net/kitty/kittens/ssh/#ssh-copy-command

### globals - avoid collisions with other people's files on shared user servers ###
# Vim
env VIMINIT=:source $HOME/my-conf/vim/vimrc
copy --dest my-conf/vim/vimrc .local/share/dotfiles/remotefs/.vimrc

