# vim:ft=kitty

# core palette
background #222436
foreground #c8d3f5
selection  #2d3f76
comment    #636da6

# normal colors
black      #1b1d2b
red        #ff757f
green      #c3e88d
yellow     #ffc777
blue       #82afff
magenta    #c099ff
cyan       #86e1fc
white      #828bb8

# UI color palette
bg_darkest  #191b29
bg_darker   #1e2030
bg_lighter  #2f334d
bg_lightest #3e68d7

# extended UI
line_highlight #292e42
border         #3b4261
active_tab_bg  #1f2335
sidebar_bg     #1f2335
status_bg      #1f2335
cursor         #c0caf5
git_added      #b8db87
git_modified   #6183bb
git_deleted    #e26a75
error          #c53b53
warning        #ffc777
info           #0db9d7

