git:
  commit:
    signOff: true
  diffRenderers:
    - command: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - type: rawGit
disableStartupPopups: true # default, no pager used
promptToReturnFromSubprocess: false
