[delta "theme"]
    dark = true
    right-arrow = >
    syntax-theme = tokyonight_night
    # -- decorations
    file-style = "#c0caf5"
    file-added-label = [+]
    file-copied-label = [==]
    file-modified-label = [*]
    file-removed-label = [-]
    file-renamed-label = [->]
    file-decoration-style = "#3b4261" overline
    hunk-header-style = file line-number syntax
    hunk-header-decoration-style = "#3b4261" box
    hunk-header-file-style = "#c099ff"
    hunk-header-line-number-style = "#3b4261" bold
    # --git
    blame-separator-format = "┊{n:>3}┊"
    blame-separator-style = "#3b4261"
    blame-palette = "# #1a1b26 #343746 #424450"
    commit-style =  "#c099ff"
    commit-decoration-style = "#3b4261" box
    # -- grep
    grep-file-style = "#3b4261"
    grep-line-number-style = "#3b4261"
    # -- diff
    line-numbers = true
    keep-plus-minus-markers = true
    line-numbers-left-style = "#3b4261"
    line-numbers-right-style = "#3b4261"
    line-numbers-zero-style = "#3b4261" italic
    line-numbers-plus-style = "#449dab"
    line-numbers-minus-style = "#914c54"
    line-numbers-left-format = "{nm:>1}┊"
    line-numbers-right-format = " {np:>1}┊"
    plus-style = syntax "#243e4a"
    plus-non-emph-style = syntax "#243e4a"
    plus-emph-style = syntax "#2c5a66"
    plus-empty-line-marker-style = syntax "#243e4a"
    minus-style = syntax "#4a272f"
    minus-non-emph-style = syntax "#4a272f"
    minus-emph-style = syntax "#713137"
    minus-empty-line-marker-style = syntax "#4a272f"
    whitespace-error-style = "#713137" reverse
    zero-style = syntax
    # colorMoved support
    map-styles = \
       bold purple => syntax "#271344", \
       bold blue => syntax "#7aa2f7", \
       bold cyan => syntax "#3284b4", \
       bold yellow => syntax "#a9b1d6"
